name: petscare
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.9

  # State & Storage
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.2.2

  # Utilities
  awesome_dialog: ^3.2.1
  http: ^0.13.5
  file_picker: ^10.1.9 # For image picking (better alternative to image_picker)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: poppins1
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppins2
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: poppins3
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
